
## FAQ

#### View Current Indicators

::: {.callout-note collapse="true" icon=false}

## My indicator isn't listed, how do I add it's metadata?

Is your indicator

*  a new indicator in an existing data file? (for example just a new species, location, etc)? If so:
    + download your metadata and add a new line for the new indicator
    + we will automatically be notified about indicators that were not previously submitted
*  an entirely new file of indicator data?
    + Do your best to format and name the data file following CCIEA conventions
    + Upload the file (@sec-upload) and notify Greg or Lynn about the new data
    + provide us metadata for the new data
    
:::

::: {.callout-note collapse="true" icon=false}

## After uploading new data and metadata, when will I see updated plots and metadata on this page?

*  Currently we run a GitHub action every morning to:
    + generate the status of all data provided so far this ESR season
    + make new plots for each provided indicator
    + merge any new metadata back into the full metadata spreadsheet
* If you don't see your updated metadata or indicator plots within the next few days after uploading:
    + check the Status page to see if your data has some issues
    + contact Lynn or Greg to see what's up!
:::

#### Download Last Year

::: {.callout-note collapse="true" icon=false}

## What's the point of downloading last year's data?

The option is provided just in case it's helpful to remember what you did a year ago! Also, we may have edited last year's file headers, etc., to follow CCIEA conventions
    
:::



#### Upload This Year

::: {.callout-note collapse="true" icon=false}

## What if my data isn't listed in the CCIEA filename convention list?

*  How do I name files for new data?
    
:::

#### File formats

::: {.callout-note collapse="true" icon=false}

## What is meant by the CCIEA "tidy" or "long" file format convention?

*  answer
    
:::

::: {.callout-note collapse="true" icon=false}

## What are the column headers for yearly data?

*  answer
    
:::

::: {.callout-note collapse="true" icon=false}

## What are the column headers for monthly data?

*  answer
    
:::

