---
title: "CCIEA Uploader Readme"
format: gfm
toc: true
---
<hr>
## California Current Integrated Ecosystem Assessment (CCIEA) Uploader

The CCIEA Uploader is an on-line resource for uploading, standardizing, and organizing CCIEA indicator data for each Ecosystem Status Report year each CCIEA Data Provider.

The uploader provides:

* Daily status of uploaded data
* View of current metadata
* Downloads of previous data and metadata
* A location to upload new data
* Real-time checks that data to be uploaded follows basic CCIEA file conventions

### Code

The code in this repository consists of GitHub actions to assemble information and updates from Google Spreadsheets and Drive, and a Quarto Website written in R and OJS.

{{< include _code_flow.qmd >}}

* **Github Action** - runs daily at 6 am
  + main.yaml: get_status.R
    - libraries: tidyverse (uses: jsonlite, tibble, dplyr, googledrive, googlesheets4)
    - loads:	_init.R, _gdrive.R, _pi_folders_to_json.R		
    - runs:
      1. check_upload()
         * check for new files in data provider upload folder
         * check file types:
           + PI metadata: incorporate back into full spreadsheet
           + data file: clean it and move to esr_year folder, plot it (work in progress)
           + other file types: just move them to esr_folder
         * Backup original files (PI_original folder)
      2. get_file_conventions()
         * input: file name conventions (Google Drive spreadsheet)
         * output: cciea_naming_conventions.json
      3. get_indices()
         * input: CCIEA Metadata (Google Drive spreadsheet)
         * output:
           + items_meta.json (for menu generation)
           + metadata.csv (complete copy of metadata)
      4. generate_file_status()
         * input: Google Drive esr_year folder for each data provider
         * output: uploader_status.json

* **Web Page** (Quarto)
  + _quarto.yml
    - uploader.qmd
      1. code: Markdown, OJS/html
      2. input:items_meta.json, cciea_naming_conventions.json
    - status.qmd
      1. code: R, OJS, flextable
      2. format: html:grid
      3. includes:
         * _pi_folders_to_df.qmd, libraries: flextable, jsonlite, tibble, officer
         *  _init.qmd
      4. input: uploader_status_[esr_year].json
          
### CCIEA Resources

* CCIEA Web pages: <https://www.integratedecosystemassessment.noaa.gov/regions/california-current>
* Ecosystem Status Reports: <https://www.integratedecosystemassessment.noaa.gov/regions/california-current/california-current-reports>
* Technical Documentation: <https://cciea-esr.github.io/ESR-Technical-Documentation-FY2025/>

